version: '3'
services:
  escritorio-db:
    container_name: escritorio-db
    image: postgres:9.6
    ports:
      - '5433:5432'
    restart: always
    environment:
      - POSTGRES_DB=escritorio-db
      - POSTGRES_PASSWORD=admin
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"